[SA-336] Doctor list: sort and filter
OkadocTech/okadoc-component-ui pull request #35
Opened 2021-09-23 12:09 UTC by maulidiyah-nur

Fix styling and behavior

2021-09-23 12:55 UTC, rioarray requested changes

2021-09-23 12:55 UTC, rioarray commented on src/components/Atoms/Select/Select.tsx
> +        console.log('blur');
please remove the console.log yaa @maulidiyah-nur

2021-09-24 01:30 UTC, rioarray commented
@maulidiyah-nur there's any conflict, please resolve that

2021-09-24 02:52 UTC, maulidiyah-nur commented
updated @rioarray

2021-09-24 03:02 UTC, rioarray approved these changes

2021-09-24 03:03 UTC, merged